platform: linux
image_resource:
  type: docker-image
  source: {repository: kiteco/concourse}
inputs:
- name: kiteco
- name: release_bin
outputs:
- name: version
- name: slack
run:
  path: kiteco/concourse/tasks/prepare-release/run.bash
params:
  platform: ((platform))
  RELEASE_DB_URI: ((release_db_uri))
