platform: linux
image_resource:
  type: docker-image
  source: {repository: kiteco/concourse}
inputs:
- name: kiteco
  path: gopath/src/github.com/kiteco/kiteco
outputs:
- name: release_bin
run:
  path: gopath/src/github.com/kiteco/kiteco/concourse/tasks/build-release-binary/run.bash
