platform: linux
image_resource:
  type: docker-image
  source: {repository: kiteco/concourse}

inputs:
- name: kiteco
- name: ((build))

outputs:
- name: tfvars

params:
  VERSIONS: ((versions))
  BUILD: ((build))

run:
  path: kiteco/concourse/tasks/tf-vars/run.bash
