apiVersion: apps/v1
kind: Deployment
metadata:
  name: kite-models
  labels:
    app: kite-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kite-models
  template:
    metadata:
      labels:
        app: kite-models
    spec:
      containers:
      - name: kite-models
        image: kiteco/tfserving
        ports:
        - containerPort: 8500
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kite-models
  labels:
    app: kite-models
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8500
  selector:
    app: kite-models
